---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

# firewalld and networkmanager come installed by default on CentOS servers and
# can interfere with networking. Ensure they are not in use.
- name: Stop and remove firewalld and networkmanager
  hosts: openstack_nodes
  tasks:
    - name: Enable PowerTools repo on CentOS8
      shell: "sudo dnf config-manager --enable powertools || sudo dnf config-manager --enable PowerTools"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
      changed_when: False

    - name: Enable CRB repo on CentOS9
      shell: "sudo dnf config-manager --enable crb"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "9"
      changed_when: False

    - name: Ensure network-scripts installed in CentOS8 as we removing NetworkManager
      package:
        name: "network-scripts"
        state: "present"
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

    - name: Stop services
      service:
        name: "{{ item }}"
        state: "stopped"
      with_items:
        - firewalld
        - NetworkManager
      ignore_errors: "yes"
      register: stopped_services

    - name: Remove services
      package:
        name: "{{ item }}"
        state: "absent"
      with_items:
        - firewalld
        - NetworkManager
      ignore_errors: "yes"

    - name: Restart networking
      service:
        name: "network"
        state: "restarted"
      when:
        - stopped_services is succeeded
        - ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

# Ensure tuned is installed and that we're using an optimal profile
# ... We're not interested in power savings
- name: Set up tuned to ensure optimal performance
  hosts: openstack_nodes
  tasks:
    - name: Ensure tuned is installed
      # amoralej - we need to add subscription-manager after bz#2029405
      package:
        name:
          - tuned
          - subscription-manager
        state: "present"

    - name: Ensure tuned is enabled and started
      service:
        name: "tuned"
        enabled: "yes"
        state: "started"

    - name: Retrieve current tuned profile
      command: tuned-adm active
      register: tuned
      changed_when: False

    - name: Print current tuned profile
      debug:
        msg: "{{ tuned.stdout }}"

    - name: Change tuned profile to throughput-performance
      command: tuned-adm profile throughput-performance
      when: "'throughput-performance' not in tuned.stdout"

- name: Set up common dependencies across all roles
  hosts: openstack_nodes
  tasks:
    - block:
      - include_role:
          name: "logs"
          tasks_from: "bootstrap"
      rescue:
        - name: Failure detected when setting up common dependencies
          fail:
            msg: "Failure detected when setting up common dependencies"
