---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

# Standalone version of the logs.yml tasks from ansible-role-ci-centos
- name: Recover logs from a ci.centos.org job
  hosts: openstack_nodes
  vars:
    api_key: "{{ lookup('env', 'CICO_API_KEY') }}"
    build_url: "{{ lookup('env', 'BUILD_URL') }}"
    build_number: "{{ lookup('env', 'BUILD_NUMBER') }}"
    job_name: "{{ lookup('env', 'JOB_NAME') }}"
    rsync_server: "rdo@artifacts.ci.centos.org::rdo"
    rsync_password: "{{ api_key | regex_replace('^(.{13}).*', '\\1') }}"
    log_root: "/var/log/weirdo"
    log_destination: "{{ log_root }}/{{ job_name }}/{{ build_number }}"
  tasks:
    - name: Fetch and gzip the console log
      shell: |
        URL="{{ build_url }}/consoleText";
        curl $URL | gzip > {{ log_destination }}/console.txt.gz
      args:
        creates: "{{ log_destination }}/console.txt.gz"
      ignore_errors: True

    - name: Upload logs to the artifact server
      environment:
        RSYNC_PASSWORD: "{{ rsync_password }}"
      shell: |
        rsync -avzR {{ log_root }}/./{{ job_name }}/{{ build_number }} \
        {{ rsync_server }} --stats
      ignore_errors: True
