---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- name: Collect logs from cico node
  hosts: openstack_nodes
  gather_facts: no
  vars:
    workspace: "{{ lookup('env', 'WORKSPACE') }}"
  tasks:
    - synchronize:
        mode: pull
        src: "/var/log/weirdo/./"
        dest: "{{ workspace }}/logs/"
        recursive: yes
        dirs: no

- name: Send logs to the log server
  hosts: logserver
  gather_facts: no
  vars:
    workspace: "{{ lookup('env', 'WORKSPACE') }}"
    destination: "{{ lookup('env', 'DESTINATION') }}"
    build_url: "{{ lookup('env', 'BUILD_URL') }}"
    log_display_url: "{{ lookup('env', 'LOG_DISPLAY_URL') }}"
  tasks:
    - name: Create log destination directory
      file:
        path: "{{ destination }}"
        state: directory
        recurse: yes

    - name: Upload logs to log server
      synchronize:
        src: "{{ workspace }}/logs"
        dest: "{{ destination }}/"
        recursive: yes
        dirs: no

    - name: Fetch and gzip the console log
      shell: |
        curl "{{ build_url }}/consoleText" | gzip > {{ destination }}/console.txt.gz
      args:
        creates: "{{ destination }}/console.txt.gz"
      ignore_errors: True

    - name: Upload ARA report
      synchronize:
        src: "{{ workspace }}/ara"
        dest: "{{ destination }}/"

    - name: Upload ARA database
      synchronize:
        src: "{{ workspace }}/ara-database"
        dest: "{{ destination }}/"

    - name: All collected logs are available following the URL below
      debug:
        var: log_display_url
